export enum Screens {
  LOGIN = "LOGIN",
  DASHBOARD = "DASHBOARD",
  SIGNUP = "SIGNUP",
  POST = "POST",
  SERVERS = "SERVERS",
  HOME = "HOME",
  POSTCREATE = "POSTCREATE",
  AddFRIENDS = "ADDFRIENDS",
  USERCONFIG = "USERCONFIG"
}
